services:
  flask:
    build: .
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./secrets.json:/app/secrets.json:ro
      - flask-data:/app/data

  homebridge:
    build:
      context: ./homebridge
    network_mode: host
    restart: unless-stopped
    volumes:
      - homebridge-data:/homebridge-data

volumes:
  homebridge-data:
  flask-data:
